include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_equals_and_hash_code_on_mutable_classes: false

analyzer:
  exclude:
    - lib/**/*.g.dart
