name: freewig
version: 0.1.2
description: >
  Freewig can be used to extract the meta data and media files from Wherigo Cartridges
homepage: https://github.com/mars3142/freewig

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.7.0

dev_dependencies:
  effective_dart: ^1.2.2
  test: ^1.14.7
