name: freewig
version: 0.0.1-dev
authors:
  - Peter Siegmund <developer@mars3142.dev>
description: >
  The library freewig will help to use Wherigo caches in Dart or Flutter
homepage: https://github.com/mars3142/freewig

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_collection: ^4.3.2
  built_value: ^6.8.2
  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.8.0
  built_value_generator: ^6.8.2
  effective_dart: ^1.0.0
  test: ^1.6.0
  mockito: ^4.0.0