name: freewig
version: 0.0.2-dev
description: >
  The library freewig will help to use Wherigo caches in Dart or Flutter
homepage: https://github.com/mars3142/freewig

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.6.0

dev_dependencies:
  effective_dart: ^1.0.0
  test: ^1.6.0
  mockito: ^4.0.0
