name: Test

on: [push]

jobs:
  build_dart_packages:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        version: ["latest", "dev"]

    runs-on: ${{ matrix.os }}

    container:
      image: google/dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings .

      - name: Run tests
        run: pub run test
